### ISSUE TITLE
The following integrations and platforms could not be set up:  tesla_gateway

### ISSUE THREAD

**Issue by benschwartz42** [carboncoop/tesla-gateway-ha-component#6]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/tesla_gateway/__init__.py:30
Integration: Tesla Gateway (documentation, issues)
First occurred: 9:01:29 PM (1 occurrences)
Last logged: 9:01:29 PM

Error during setup of component tesla_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/tesla_gateway/__init__.py", line 30, in async_setup
    domain_config = config[DOMAIN]
KeyError: 'tesla_gateway'

**Comment by benschwartz42** [comment]
Updated to 2021.5.0

**Comment by ericrubino** [comment]
I have this exact same error when trying to set this up for the very first time after installing Home Assistant and HACS a couple of hours prior. Am I doing something incorrect or is there an issue?

Logger: homeassistant.setup
Source: custom_components/tesla_gateway/__init__.py:30
Integration: Tesla Gateway (documentation, issues)
First occurred: 8:19:25 PM (1 occurrences)
Last logged: 8:19:25 PM

Error during setup of component tesla_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 248, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/tesla_gateway/__init__.py", line 30, in async_setup
    domain_config = config[DOMAIN]
KeyError: 'tesla_gateway'

**Comment by oldironUK** [comment]
Same problem:

2021-07-08 18:07:08 ERROR (MainThread) [homeassistant.setup] Error during setup of component tesla_gateway
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 249, in _async_setup_component
result = await task
File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
res = func(*args, **kw)
File "/config/custom_components/tesla_gateway/__init__.py", line 30, in async_setup
domain_config = config[DOMAIN]
KeyError: 'tesla_gateway'

(Just for reference in the meantime I successfully installed the HA Tesla car integration and the HA local powerwall viewer integration.)

**Comment by craigrouse** [comment]
Same issue here

**Comment by ryangottlieb** [comment]
I am having this issue too.

**Comment by stevesreed** [comment]
I have this issue as well

**Comment by beardboy69** [comment]
I have the same issue too;

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/tesla_gateway/__init__.py:30
Integration: Tesla Gateway (documentation, issues)
First occurred: 16:43:16 (1 occurrences)
Last logged: 16:43:16

Error during setup of component tesla_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/tesla_gateway/__init__.py", line 30, in async_setup
    domain_config = config[DOMAIN]
KeyError: 'tesla_gateway'

Looking above, lots of us do but there are no replies here showing the resolution?

Any ideas?

**Comment by beardboy69** [comment]
I've been playing some more to try and get this running, but am getting this error now so I think i'm getting closer to getting it working!

2022-07-25 11:40:04 WARNING (SyncWorker_2) [homeassistant.loader] We found a custom integration tesla_gateway which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-07-25 11:40:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Tesla Gateway for tesla_gateway
AttributeError: module 'custom_components.tesla_gateway' has no attribute 'async_setup_entry'

**Comment by Roaders** [comment]
same here. Looks like this component is abandonware. :-(

**Comment by craigrouse** [comment]
@Roaders I'd suggest the excellent [Tesla Custom](https://github.com/alandtse/tesla/) integration, which supports both energy products and vehicles. Much easier to set up and use, and is actively maintained.
