### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by HeraldCoupe** [carboncoop/tesla-gateway-ha-component#7]
I've been using this integration without a problem on Home Assistant OS 5.13 supervisor-2021.06.3 version: core-2021.4.6 but when I upgrade to Home Assistant OS 6.0 supervisor-2021.06.3 version: core-2021.6.5 I get the following error on the log. Any idea what I need to do to fix it?

Error setting up entry Tesla Gateway for tesla_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
AttributeError: module 'custom_components.tesla_gateway' has no attribute 'async_setup_entry'

**Comment by rowan-OzRunways** [comment]
+1 identical issue, new install

**Comment by craigrouse** [comment]
@HeraldCoupe @rowan-OzRunways did either of you manage to get this resolved? I have the same issue and can't figure it out.

**Comment by HeraldCoupe** [comment]
I've not made any progress at all. I was waiting to hear from others more expert than me but nothing so far.

**Comment by nonlinearsugar** [comment]
I'm getting slightly different but mostly similar errors on my new component installation.

2021-11-02 08:31:32 ERROR (MainThread) [homeassistant.setup] Error during setup of component tesla_gateway
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File "/config/custom_components/tesla_gateway/__init__.py", line 30, in async_setup
    domain_config = config[DOMAIN]
KeyError: 'tesla_gateway'

**Comment by craigrouse** [comment]
I wrote up how I was able to fix it here: https://community.home-assistant.io/t/add-support-for-tesla-powerwall/142280/190. Hope this helps.

**Comment by HeraldCoupe** [comment]
My update:
I was running the integration on Home Assistant OS 5.13 supervisor-2021.06.3 version: core-2021.4.6 until today when the Pi failed.
I already had another Pi running Home Assistant OS 7.9 supervisor-2021.12.2 version: core-2021.12.5 with the integration installed from when I tried to get it running back in June (when I had the problems above)
I did nothing other than simply try the integration again and to my surprise it worked. I can only surmise that the problem that was introduced in HA was subsequently fixed in a later version.

**Comment by purcell-lab** [comment]
> I wrote up how I was able to fix it here: https://community.home-assistant.io/t/add-support-for-tesla-powerwall/142280/190. Hope this helps.

@craigrouse you seem to have functional modifications, I would be happy to manage a PR/ fork to get something back into github that is functional.

I have followed your processes in community.home-assistant without success.

Can you please followup here with your current functional configuration __init.py__ and any other changes so I can load as a PR/ fork?

**Comment by craigrouse** [comment]
@purcell-lab I was considering forking this too, but just not had the time to do it yet. I don't have any functional modifications, only enough to get it working. Ideally we'd integrate the whole authentication flow so it's not necessary to manually generate a token. Recently, I had to upgrade the teslapy dependency, which required a change to some of the method signatures in the init.py. I'll follow up later with my changes.
